package org.example.springbootmybaties;

import org.mybatis.spring.annotation.MapperScan;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
//spring boot核心启动注解
@SpringBootApplication
//告诉框架我的项目中的mapper层的包的路径（必不可少）mapper层一行代码不用写
@MapperScan("org.example.springbootmybaties.mapper")
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

}

