# 数据库驱动
db.driver=com.mysql.cj.jdbc.Driver
# 数据库连接URL
db.url=jdbc:mysql://localhost:3306/store_inventory?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
# 数据库用户名
db.username=root
# 数据库密码
db.password=123456